### PR TITLE
William/fix monero

### PR DESCRIPTION
**Pull request by swansontec**
Here are fixes for some problems I encountered during the Monero upgrade. This is not the Monero upgrade itself yet.

### CODE REVIEW

**Comment by paullinator** [comment]
The binary files shrunk a LOT. Is this expected? Almost as if monero was fully removed?

**Comment by swansontec** [comment]
I don't know why they would be smaller. I just ran the build scripts as usual. This particular version seems to run correctly on my phone, too.

**Comment by paullinator** [comment]
Just want to make sure the following was tested as there are a lot of platforms that this affects:
iPhone 5 simulator (32bit x86)
iPhone 6+ simulator (64bit x86)
iPhone 6+ (64bit ARM)
Android Genymotion (32bit x86)
Android Pixel/Samsung/Nexus (32bit ARM)

or we could just publish a -beta.0 release and have QA bang at it.

**Review by paullinator — CHANGES_REQUESTED** [review]
Don't you need to bump the version at the top of mymonerocorecpp.recipe?

**Comment by swansontec** [comment]
The binaries are from a clean build on my machine. After deep-diving into the size difference on iOS, it looks like your build (current master) has a debug version of mymonerocorecpp for x86_64, since it's randomly 6 megs larger than the other architectures for that bundle.

**Review by paullinator — APPROVED** [review]

**Pull request merged**
